[package]
name = "subdomain_remover"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4.0"
fancy-regex = "0.11.0"

[build-dependencies]
winres = "0.1"